coverage:
  ignore:
    - "compiler/chore"
    - "compiler/cmd/internal"
    - "compiler/internal/build"
    - "compiler/internal/llgen"
    - "compiler/internal/mockable"
    - "compiler/internal/packages"
    - "compiler/internal/typepatch"
